### ISSUE TITLE
배포 설정

### ISSUE THREAD

**Issue by 1000peach** [Nexters/TILTIL_FRONT#41]
제가 aws docker 배포에 배움이 필요하여,,,
요 이슈는 다른 사람 어싸인하고 같이 보는 게 좋을 거 같다는 생각에,,,
오늘 오지 못한 건우님을 몰ㄹ ㅐ 어싸인해봅니다,,, 😇

**Comment by zi-gae** [comment]
승아님 구석진대로 따라오시져
